version: '3'

services:
  web:
    image: python:3.10
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
    # - .:/app
      - ./api:/app/api
      - ./manage.py:/app/manage.py
      - /app/frontend/node_modules
    ports:
      - "8003:8000"